site_name: Statue
site_description: 'Statue - Orchestration tool for static code analysis'
repo_url: https://github.com/saroad2/statue
theme:
  name: material
nav:
  - Home: README.md
  - Tutorials:
      - Quick Start: quick_start.md
      - Run Efficiently: run_efficiently.md
      - It's All A Matter of Context: contexts.md
markdown_extensions:
  - admonition
plugins:
  - macros:
      module_name: docs/mkdocs_macros
  - search