site_name: Statue
site_description: 'Statue - Orchestration tool for static code analysis'
repo_url: https://github.com/saroad2/statue
theme:
  name: material
nav:
  - Home: README.md
  - Tutorials:
      - Quick Start: tutorials/quick_start.md
      - Run Efficiently: tutorials/run_efficiently.md
      - It's All A Matter of Context: tutorials/contexts.md
      - Configurate It: tutorials/configuration.md
  - Advanced:
      - Taking Contexts to The Next Level: advanced/advanced_contexts.md
      - Run On Steroids: advanced/advanced_run.md
      - User Templates: advanced/user_templates.md
  - CLI References: cli_references.md
  - Templates: templates.md
markdown_extensions:
  - admonition
  - attr_list
  - mkdocs-click
plugins:
  - macros:
      module_name: docs/mkdocs_macros
  - search
extra:
    version: 0.0.18