site_name: Statue
site_description: 'Statue - Orchestration tool for static code analysis'
repo_url: https://github.com/saroad2/statue
theme: material
nav:
  - Home: README.md
  - Tutorials:
      - Quick Start: quick_start.md
plugins:
  - macros
  - search
extra:
  version: 0.0.18