[general]
mode = "sync"

[contexts.fast]
help = "Run short-time commands. Good for smoke tests"

[contexts.strict]
help = "Strict checks, for ones who never compromise!"
allowed_by_default = true

[contexts.format]
help = "Reformating commands, with in-file replacements."
aliases = [ "fmt",]

[contexts.test]
help = "Checks for test files."

[contexts.documentation]
help = "Commands regarding code documentation."
aliases = [ "docs",]

[commands.black]
help = "Code formatter for python."
version = "22.1.0"
args = [ "--check",]
allowed_contexts = [ "fast", "test",]

[commands.flake8]
help = "Code style checker for python."
version = "4.0.1"
args = [ "--max-line-length=88", "--ignore=E203,W503,DAR",]
allowed_contexts = [ "fast", "test",]

[commands.autoflake]
help = "Remove unused imports and variables"
version = "1.4"
args = [ "--in-place", "--recursive", "--expand-star-imports", "--remove-all-unused-imports",]
required_contexts = [ "format",]
allowed_contexts = [ "fast", "format", "test",]

[commands.isort]
help = "Tool for sorting and cleaning python imports."
version = "5.10.1"
args = [ "--profile=black", "--check-only",]
allowed_contexts = [ "fast", "test",]

[commands.mypy]
help = "Validate types using mypy."
version = "0.942"
args = [ "--ignore-missing-imports",]
allowed_contexts = [ "test",]

[commands.pylint]
help = "Python code linter"
version = "2.13.0"
args = [ "--ignore-imports=y", "--disable=bad-continuation", "--enable=useless-suppression", "--fail-on=useless-suppression",]
allowed_contexts = [ "documentation",]

[commands.bandit]
help = "Python security checks tool."
version = "1.7.4"
args = [ "-r", "--skip=B603",]

[commands.pydocstyle]
help = "Tool for python docstring style enforcing"
version = "6.1.1"
args = [ "--ignore=D203,D212,D400,D401",]
allowed_contexts = [ "documentation",]

[commands.darglint]
help = "Tool for documentation coverage."
version = "1.8.1"
args = [ "--docstring-style=sphinx", "--ignore-regex=.*_cli", "--ignore-properties",]
allowed_contexts = [ "documentation",]

[sources."setup.py"]
contexts = [ "fast",]

[sources."src/statue"]

[sources.tests]
contexts = [ "test",]

[commands.black.format]
clear_args = true

[commands.isort.format]
args = [ "--profile=black",]

[commands.mypy.strict]
add_args = [ "--strict",]

[commands.pylint.test]
add_args = [ "--disable=C0103,C0114,C0115,C0116,C0203,C0204,C0330,C0411", "--disable=E0401,E0611,E1101,E1120,E1130,E1139", "--disable=R0801,R0902,R0903,R0904,R0913", "--disable=W0201,W0613,W0621",]
