[commands.darglint]
add_args = [ "--ignore-regex=.*_cli",]
version = "1.8.1"

[commands.black]
version = "21.11b1"

[commands.flake8]
version = "4.0.1"

[commands.isort]
version = "5.10.1"

[commands.mypy]
version = "0.910"

[commands.pylint]
version = "2.9.0"

[commands.bandit]
version = "1.7.1"

[commands.pydocstyle]
version = "6.1.1"

[commands.autoflake]
version = "1.4"

[sources."setup.py"]
contexts = [ "fast",]

[sources."src/statue"]
contexts = [ "standard",]

[sources.tests]
contexts = [ "test",]
